# Permalinks
permalink: "/articles/:title/"

# Setup
exclude:          ['bower_components', 'node_modules']
title:            ZS Labs
tagline:          "Personal blog of Zach Schnackel"
paginate:         1
author:
  name:           "Zach Schnackel"
  url:            "https://twitter.com/zslabs"
  email:          "info@zslabs.com"
