# Permalinks
permalink: "/articles/:title/"

# Server
url: "https://zslabs.com"
encoding: UTF-8

# Setup
exclude:          
  - bower_components
  - node_modules
title: ZS Labs
tagline: "Personal blog of Zach Schnackel"
author:
  name: "Zach Schnackel"
  url: "https://twitter.com/zslabs"
  email: "info@zslabs.com"
