title: ZS Labs

baseurl: ''

url: https://zslabs.com

tagline: Personal blog and portfolio of developer Zach Schnackel.

# Permalinks
permalink: articles/:title/

# Setup
exclude:          
  - bower_components
  - node_modules

author:
  name: Zach Schnackel
  url: https://twitter.com/zslabs
  email: info@zslabs.com
